### ISSUE TITLE
bridge plugin crashing in the cleaner code

### ISSUE THREAD

**Issue by yuvalif** [mpolednik/linux-vfio-k8s-dpi#44]
when running the new tests from kubevirt. see PR: https://github.com/kubevirt/kubevirt/pull/1342
run:
```
FUNC_TEST_ARGS='-ginkgo.focus=vmi_bridge_test -ginkgo.regexScansFilePath' make functest
```

logs from plugin pod:
```
panic: failed to bind unix socket: address already in use

goroutine 15 [running]:
github.com/kubevirt/kubernetes-device-plugins/pkg/network/bridge.(*cleaner).Run(0xc42000c1a0)
	/home/travis/gopath/src/github.com/kubevirt/kubernetes-device-plugins/pkg/network/bridge/cleaner.go:74 +0x149
created by github.com/kubevirt/kubernetes-device-plugins/pkg/network/bridge.(*NetworkBridgeDevicePlugin).Start
	/home/travis/gopath/src/github.com/kubevirt/kubernetes-device-plugins/pkg/network/bridge/plugin.go:62 +0xd3
```

**Comment by yuvalif** [comment]
The problem is that currently we try to create a monitor per resource (per device plugin) and not per pod (PID). So, a pod has multiple processes, it will try to create multiple monitors with the same unix socket address (the PID).

**Comment by phoracek** [comment]
The original cleanup code was removed. Closing
